### ISSUE TITLE
セキュリティ寿司次は行きたい

### ISSUE THREAD

**Issue by hasegawayosuke** [efcl/efcl.github.io#129]
ので、もしよければ次回は呼んでほしいです！

**Comment by Jxck** [comment]
+1

**Comment by teppeis** [comment]
:sushi: :+1:

**Comment by azu** [comment]
:ok:

**Comment by Jxck** [comment]
6/1, 2, 3 あたりどうです？

**Comment by hasegawayosuke** [comment]
その期間はバタバタしていてごめんなさい。翌週6/6-6/9あたりであれば！

**Comment by yosuke-furukawa** [comment]
6/7, 6/8, 6/9 空いてます！

**Comment by Jxck** [comment]
bote required !

https://twitter.com/Jxck_/status/734971085045653504

**Comment by Jxck** [comment]
6/9(木) でどうでしょう？

**Comment by yosuke-furukawa** [comment]
+1

**Comment by Jxck** [comment]
じゃあ 6/9 19:30 で。次の場所は三軒茶屋でも開拓するか。

**Comment by hasegawayosuke** [comment]
うおー、日程確定した直後で申しわけないです、その日に別件はいりそうで不確定な感じになりました＞＜
その後もバタバタと高知にいったりなので、申しわけないですけど7月に改めて仕切り直しでもいいでしょうか？
すみません＞＜

**Comment by Jxck** [comment]
では 7 月で！

**Comment by hasegawayosuke** [comment]
m(_ _)m
